name: AWS-Zig Build
run-name: ${{ github.actor }} building ddblocal
on:
  push:
    branches:
      - '*'
      - '!zig-develop*'
env:
  ACTIONS_RUNTIME_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ACTIONS_RUNTIME_URL: ${{ env.GITHUB_SERVER_URL }}/api/actions_pipeline/
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: elerch/setup-zig@v3
        with:
          version: 0.12.0
      - uses: elerch/zig-action-cache@v1.1.6
      - name: Standard build
        run: zig build --verbose
      - name: Run tests
        run: zig build test --verbose
      - name: Build other platforms
        run: |
          zig build -Dtarget=aarch64-macos
          zig build -Dtarget=x86_64-macos
          zig build -Dtarget=x86_64-windows
          zig build -Dtarget=aarch64-linux
          zig build -Dtarget=riscv64-linux
          zig build -Dtarget=x86_64-linux
      # - name: Sign
      #   id: sign
      #   uses: https://git.lerch.org/lobo/action-hsm-sign@v1
      #   with:
      #     pin: ${{ secrets.HSM_USER_PIN }}
      #     files: ???
      #     public_key: 'https://emil.lerch.org/serverpublic.pem'
      # - run: |
      #     echo "Source 0 should be ./bar: ${{ steps.sign.outputs.SOURCE_0 }}"
      # - run: |
      #     echo "Signature 0 should be ./bar.sig: ${{ steps.sign.outputs.SIG_0 }}"
      # - run: echo "URL of bar (0) is ${{ steps.sign.outputs.URL_0 }}"
      # - run: |
      #     echo "Source 1 should be ./foo: ${{ steps.sign.outputs.SOURCE_1 }}"
      # - run: |
      #     echo "Signature 1 should be ./foo.sig: ${{ steps.sign.outputs.SIG_1 }}"
      # - run: echo "URL of foo (1) is ${{ steps.sign.outputs.URL_1 }}"
      - name: Notify
        uses: elerch/action-notify-ntfy@v2.github
        if: always() && env.GITEA_ACTIONS == 'true'
        with:
          host: ${{ secrets.NTFY_HOST }}
          topic: ${{ secrets.NTFY_TOPIC }}
          status: ${{ job.status }}
          user: ${{ secrets.NTFY_USER }}
          password: ${{ secrets.NTFY_PASSWORD }}
